export const ACCOUNTS_LEGAL_URL = 'https://accounts.aoctech.app/legal'
export const PRIVACY_POLICY_URL = 'https://accounts.aoctech.app/privacy'
export const WALLET_TERMS_URL = 'https://accounts.aoctech.app/products/wallet'
export const WALLET_GAMING_TERMS_URL = 'https://accounts.aoctech.app/products/wallet-gaming'
export const CVV_PHONE_URL = 'tel:188'
export const CVV_URL = 'https://www.cvv.org.br'
export const GAMBLERS_ANONYMOUS_URL = 'https://jogadoresanonimos.com.br'
